### ISSUE TITLE
Support kubeconfig file on API client

### ISSUE THREAD

**Issue by spiddy** [Goyoo/node-k8s-client#27]
I'm working on a PR to add support for passing kubeconfig on the API client, similar to the binary client:

```js
// Configure using kubeconfig
var kubeapi = K8s.api({
    kubeconfig: kubeconfigJSON
    ,version: '/api/v1'
})
```

so that an end-user can simply point to the existing kubeconfig and connect. Initially I wanted to follow same format as in binary client, but to avoid adding dependencies to read file and parse JSON, I'm thinking to use as input field an already parsed JSON format, though this diverges from the binary params.

**Comment by spiddy** [comment]
Update: Using JSON as input is not possible, since `kubeconfig` may have reference to files (example below) that also need to be read

```
- cluster:
    certificate-authority: /Users/spiddy/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
```

In order for this to work we need to add libraries to read files and parse JSON, though I really like the minimalistic approach of dependencies currently. Should we add this to the scope of the project?
